[package]
name = "Echo pop coin"
version = "1.0.0"
license = "MIT"

[addresses]
std="0x1"
aptos_framework="0x1"
aptos_std="0x1"
PopCoin = "_"

[dependencies]
AptosFramework = { local = "../../../../aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "../../../../aptos-core/aptos-move/framework/aptos-stdlib" }
